<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Tool;
use App\Models\ToolTag;

class ToolSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $tools = [
            // Image Tools (category_id: 1)
            [
                'category_id' => 1,
                'name' => 'Image Compressor',
                'slug' => 'image-compressor',
                'icon' => '🗜️',
                'description' => 'Compress images without losing quality. Reduce file size for faster loading.',
                'url' => '/tools/image-compressor',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '1.2M',
                'color' => 'b',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Image Resizer',
                'slug' => 'image-resizer',
                'icon' => '📐',
                'description' => 'Resize images to any dimension. Perfect for social media and web.',
                'url' => '/tools/image-resizer',
                'tags' => ['free', 'web-based', 'beginner-friendly'],
                'tool_count' => '980K',
                'color' => 'g',
                'display_order' => 2,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Background Remover',
                'slug' => 'background-remover',
                'icon' => '✂️',
                'description' => 'Remove background from images automatically using AI.',
                'url' => '/tools/background-remover',
                'tags' => ['premium', 'web-based', 'api-available'],
                'tool_count' => '750K',
                'color' => 'p',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 1,
                'name' => 'Image Format Converter',
                'slug' => 'image-format-converter',
                'icon' => '🔄',
                'description' => 'Convert images between formats: JPG, PNG, WebP, GIF, and more.',
                'url' => '/tools/image-format-converter',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '650K',
                'color' => 'o',
                'display_order' => 4,
                'is_featured' => false,
                'is_active' => true,
            ],

            // PDF Tools (category_id: 2)
            [
                'category_id' => 2,
                'name' => 'PDF Merger',
                'slug' => 'pdf-merger',
                'icon' => '📑',
                'description' => 'Merge multiple PDF files into one document easily.',
                'url' => '/tools/pdf-merger',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '1.5M',
                'color' => 'r',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'PDF Splitter',
                'slug' => 'pdf-splitter',
                'icon' => '✂️',
                'description' => 'Split PDF files into separate pages or extract specific pages.',
                'url' => '/tools/pdf-splitter',
                'tags' => ['free', 'web-based', 'beginner-friendly'],
                'tool_count' => '890K',
                'color' => 'b',
                'display_order' => 2,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'PDF to Word',
                'slug' => 'pdf-to-word',
                'icon' => '📄',
                'description' => 'Convert PDF documents to editable Word files.',
                'url' => '/tools/pdf-to-word',
                'tags' => ['premium', 'web-based', 'api-available'],
                'tool_count' => '1.1M',
                'color' => 'g',
                'display_order' => 3,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 2,
                'name' => 'PDF Compressor',
                'slug' => 'pdf-compressor',
                'icon' => '🗜️',
                'description' => 'Reduce PDF file size while maintaining quality.',
                'url' => '/tools/pdf-compressor',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '720K',
                'color' => 'p',
                'display_order' => 4,
                'is_featured' => false,
                'is_active' => true,
            ],

            // Text Tools (category_id: 3)
            [
                'category_id' => 3,
                'name' => 'Word Counter',
                'slug' => 'word-counter',
                'icon' => '📝',
                'description' => 'Count words, characters, sentences, and paragraphs in your text.',
                'url' => '/tools/word-counter',
                'tags' => ['free', 'web-based', 'no-signup', 'beginner-friendly'],
                'tool_count' => '2.3M',
                'color' => 'g',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Case Converter',
                'slug' => 'case-converter',
                'icon' => '🔤',
                'description' => 'Convert text to uppercase, lowercase, title case, and more.',
                'url' => '/tools/case-converter',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '1.8M',
                'color' => 'b',
                'display_order' => 2,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Text Formatter',
                'slug' => 'text-formatter',
                'icon' => '✨',
                'description' => 'Format and clean up text with various options.',
                'url' => '/tools/text-formatter',
                'tags' => ['free', 'web-based', 'beginner-friendly'],
                'tool_count' => '950K',
                'color' => 'o',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 3,
                'name' => 'Lorem Ipsum Generator',
                'slug' => 'lorem-ipsum-generator',
                'icon' => '📄',
                'description' => 'Generate placeholder text for your designs and mockups.',
                'url' => '/tools/lorem-ipsum-generator',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '680K',
                'color' => 'p',
                'display_order' => 4,
                'is_featured' => false,
                'is_active' => true,
            ],

            // Color Tools (category_id: 4)
            [
                'category_id' => 4,
                'name' => 'Color Picker',
                'slug' => 'color-picker',
                'icon' => '🎨',
                'description' => 'Pick colors and get HEX, RGB, HSL codes instantly.',
                'url' => '/tools/color-picker',
                'tags' => ['free', 'web-based', 'no-signup', 'beginner-friendly'],
                'tool_count' => '1.6M',
                'color' => 'r',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Gradient Generator',
                'slug' => 'gradient-generator',
                'icon' => '🌈',
                'description' => 'Create beautiful CSS gradients with live preview.',
                'url' => '/tools/gradient-generator',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '1.2M',
                'color' => 'g',
                'display_order' => 2,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 4,
                'name' => 'Color Palette Generator',
                'slug' => 'color-palette-generator',
                'icon' => '🎭',
                'description' => 'Generate harmonious color palettes for your projects.',
                'url' => '/tools/color-palette-generator',
                'tags' => ['free', 'web-based', 'beginner-friendly'],
                'tool_count' => '890K',
                'color' => 'b',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],

            // CSS Tools (category_id: 5)
            [
                'category_id' => 5,
                'name' => 'CSS Minifier',
                'slug' => 'css-minifier',
                'icon' => '⚡',
                'description' => 'Minify CSS code to reduce file size and improve performance.',
                'url' => '/tools/css-minifier',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '780K',
                'color' => 'b',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Box Shadow Generator',
                'slug' => 'box-shadow-generator',
                'icon' => '📦',
                'description' => 'Create CSS box shadows with live preview.',
                'url' => '/tools/box-shadow-generator',
                'tags' => ['free', 'web-based', 'beginner-friendly'],
                'tool_count' => '650K',
                'color' => 'g',
                'display_order' => 2,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 5,
                'name' => 'Border Radius Generator',
                'slug' => 'border-radius-generator',
                'icon' => '⭕',
                'description' => 'Generate CSS border radius with visual editor.',
                'url' => '/tools/border-radius-generator',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '520K',
                'color' => 'o',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],

            // Code Tools (category_id: 6)
            [
                'category_id' => 6,
                'name' => 'JSON Formatter',
                'slug' => 'json-formatter',
                'icon' => '{ }',
                'description' => 'Format and validate JSON data with syntax highlighting.',
                'url' => '/tools/json-formatter',
                'tags' => ['free', 'web-based', 'no-signup', 'beginner-friendly'],
                'tool_count' => '2.1M',
                'color' => 'g',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 6,
                'name' => 'Code Beautifier',
                'slug' => 'code-beautifier',
                'icon' => '✨',
                'description' => 'Beautify HTML, CSS, JavaScript, and more.',
                'url' => '/tools/code-beautifier',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '1.4M',
                'color' => 'b',
                'display_order' => 2,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 6,
                'name' => 'Base64 Encoder/Decoder',
                'slug' => 'base64-encoder-decoder',
                'icon' => '🔐',
                'description' => 'Encode and decode Base64 strings easily.',
                'url' => '/tools/base64-encoder-decoder',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '920K',
                'color' => 'p',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],

            // Converter Tools (category_id: 7)
            [
                'category_id' => 7,
                'name' => 'Unit Converter',
                'slug' => 'unit-converter',
                'icon' => '📏',
                'description' => 'Convert between different units of measurement.',
                'url' => '/tools/unit-converter',
                'tags' => ['free', 'web-based', 'no-signup', 'beginner-friendly'],
                'tool_count' => '1.9M',
                'color' => 'g',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 7,
                'name' => 'Currency Converter',
                'slug' => 'currency-converter',
                'icon' => '💱',
                'description' => 'Convert currencies with real-time exchange rates.',
                'url' => '/tools/currency-converter',
                'tags' => ['free', 'web-based', 'api-available'],
                'tool_count' => '1.7M',
                'color' => 'b',
                'display_order' => 2,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 7,
                'name' => 'Timestamp Converter',
                'slug' => 'timestamp-converter',
                'icon' => '⏰',
                'description' => 'Convert Unix timestamps to readable dates and vice versa.',
                'url' => '/tools/timestamp-converter',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '850K',
                'color' => 'o',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],

            // Generator Tools (category_id: 8)
            [
                'category_id' => 8,
                'name' => 'QR Code Generator',
                'slug' => 'qr-code-generator',
                'icon' => '📱',
                'description' => 'Generate QR codes for URLs, text, and more.',
                'url' => '/tools/qr-code-generator',
                'tags' => ['free', 'web-based', 'no-signup', 'beginner-friendly'],
                'tool_count' => '2.5M',
                'color' => 'g',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 8,
                'name' => 'Password Generator',
                'slug' => 'password-generator',
                'icon' => '🔑',
                'description' => 'Generate strong, secure passwords instantly.',
                'url' => '/tools/password-generator',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '1.8M',
                'color' => 'r',
                'display_order' => 2,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 8,
                'name' => 'UUID Generator',
                'slug' => 'uuid-generator',
                'icon' => '🆔',
                'description' => 'Generate unique identifiers (UUID/GUID).',
                'url' => '/tools/uuid-generator',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '680K',
                'color' => 'b',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],

            // SEO Tools (category_id: 9)
            [
                'category_id' => 9,
                'name' => 'Meta Tag Generator',
                'slug' => 'meta-tag-generator',
                'icon' => '🏷️',
                'description' => 'Generate SEO-friendly meta tags for your website.',
                'url' => '/tools/meta-tag-generator',
                'tags' => ['free', 'web-based', 'no-signup', 'beginner-friendly'],
                'tool_count' => '1.3M',
                'color' => 'g',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 9,
                'name' => 'Keyword Density Checker',
                'slug' => 'keyword-density-checker',
                'icon' => '🔍',
                'description' => 'Analyze keyword density in your content.',
                'url' => '/tools/keyword-density-checker',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '890K',
                'color' => 'b',
                'display_order' => 2,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 9,
                'name' => 'Robots.txt Generator',
                'slug' => 'robots-txt-generator',
                'icon' => '🤖',
                'description' => 'Generate robots.txt file for your website.',
                'url' => '/tools/robots-txt-generator',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '620K',
                'color' => 'o',
                'display_order' => 3,
                'is_featured' => false,
                'is_active' => true,
            ],

            // Security Tools (category_id: 10)
            [
                'category_id' => 10,
                'name' => 'Hash Generator',
                'slug' => 'hash-generator',
                'icon' => '🔐',
                'description' => 'Generate MD5, SHA1, SHA256 hashes for text and files.',
                'url' => '/tools/hash-generator',
                'tags' => ['free', 'web-based', 'no-signup'],
                'tool_count' => '1.1M',
                'color' => 'r',
                'display_order' => 1,
                'is_featured' => true,
                'is_active' => true,
            ],
            [
                'category_id' => 10,
                'name' => 'SSL Checker',
                'slug' => 'ssl-checker',
                'icon' => '🔒',
                'description' => 'Check SSL certificate details and validity.',
                'url' => '/tools/ssl-checker',
                'tags' => ['free', 'web-based', 'api-available'],
                'tool_count' => '750K',
                'color' => 'g',
                'display_order' => 2,
                'is_featured' => false,
                'is_active' => true,
            ],
            [
                'category_id' => 10,
                'name' => 'Password Strength Checker',
                'slug' => 'password-strength-checker',
                'icon' => '💪',
                'description' => 'Check the strength of your passwords.',
                'url' => '/tools/password-strength-checker',
                'tags' => ['free', 'web-based', 'no-signup', 'beginner-friendly'],
                'tool_count' => '980K',
                'color' => 'b',
                'display_order' => 3,
                'is_featured' => true,
                'is_active' => true,
            ],
        ];

        foreach ($tools as $toolData) {
            $tool = Tool::create($toolData);
            
            // Attach tags to the tool using the pivot table
            if (!empty($toolData['tags'])) {
                $tagIds = ToolTag::whereIn('slug', $toolData['tags'])->pluck('id')->toArray();
                $tool->toolTags()->attach($tagIds);
            }
        }
    }
}
